global:
  licenseKey: ${NEW_RELIC_LICENSE_KEY}
  cluster: bion-eks

newrelic-infrastructure:
  enabled: true
  privileged: true

kube-state-metrics:
  enabled: true

prometheus:
  enabled: true

nri-metadata-injection:
  enabled: true

newrelic-logging:
  enabled: true
  lowDataMode: true

pixie:
  enabled: false

# Enable application instrumentation for demonstration
nri-prometheus:
  enabled: true
  config:
    integrations:
      - name: nri-prometheus
        config:
          metric_api_endpoint: /api/v1/metrics
          scrape_configs:
            - job_name: 'voting-app'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_namespace]
                  action: keep
                  regex: voting-app
                - source_labels: [__meta_kubernetes_pod_label_app]
                  action: keep
                  regex: (vote|result|worker|redis|db)
                - source_labels: [__meta_kubernetes_pod_label_app]
                  action: replace
                  target_label: app
                - source_labels: [__meta_kubernetes_pod_name]
                  action: replace
                  target_label: pod_name