name: Docker Image Build and Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

#imagen 1
    - name: Build the Docker image 1
      run: docker build . --file ./vote/Dockerfile --tag vote

    - name: Scan image 1
      id: scan1
      uses: sysdiglabs/scan-action@v5
      with:
        image-tag: vote:latest
        sysdig-secure-token: 98513912-9a2c-4f60-a5ba-2c424565e793 #${{ secrets.SYSDIG_SECURE_TOKEN }}
        sysdig-secure-url: https://eu1.app.sysdig.com
        #sarif-output-file: ${{ github.workspace }}/sarif.json
#imagen 2
    - name: Build the Docker image 2
      run: docker build . --file ./result/Dockerfile --tag result

    - name: Scan image 2
      id: scan2
      uses: sysdiglabs/scan-action@v5
      with:
        image-tag: result:latest
        sysdig-secure-token: 98513912-9a2c-4f60-a5ba-2c424565e793 #${{ secrets.SYSDIG_SECURE_TOKEN }}
        sysdig-secure-url: https://eu1.app.sysdig.com
        #sarif-output-file: ${{ github.workspace }}/sarif.json
#imagen 3
    - name: Build the Docker image 3
      run: docker build . --file ./worker/Dockerfile --tag worker

    - name: Scan image 3
      id: scan3
      uses: sysdiglabs/scan-action@v5
      with:
        image-tag: worker:latest
        sysdig-secure-token: 98513912-9a2c-4f60-a5ba-2c424565e793 #${{ secrets.SYSDIG_SECURE_TOKEN }}
        sysdig-secure-url: https://eu1.app.sysdig.com
        #sarif-output-file: ${{ github.workspace }}/sarif.json

